[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install poetry",
  "poetry config virtualenvs.create false",
  "poetry install --only main --no-interaction"
]

[phases.build]
cmds = [
  "python -m spacy download en_core_web_sm"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
